/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package db_project_2022;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileNotFoundException;
import java.sql.*;
import java.util.HashSet;
import java.util.LinkedList;
import java.util.Scanner;

/**

 @author Panagiotis
 */
public class LoginWindow extends javax.swing.JFrame
{

	/**
	 Creates new form NewJFrame
	 */
	public LoginWindow()
	{
		this.setTitle("Login");
		initComponents();
		
		Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
		int xpos = (int)((dimension.getWidth() - this.getWidth()) / 2);
		int ypos = (int)((dimension.getHeight() - this.getHeight()) / 2);
		this.setLocation(new java.awt.Point(xpos, ypos));
		
		loginErrorLabel.setText("");
		loadCredentials();
	}

	/**
	 This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings ("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        loginButton = new javax.swing.JButton();
        usernameField = new javax.swing.JTextField();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        passwordField = new javax.swing.JPasswordField();
        showPasswordBox = new java.awt.Checkbox();
        loginErrorLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        label1 = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);

        loginButton.setText("LOGIN");
        loginButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                loginButtonActionPerformed(evt);
            }
        });

        usernameField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        usernameField.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                usernameFieldKeyPressed(evt);
            }
        });

        label2.setText("Username");

        label3.setText("Password");

        passwordField.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                passwordFieldKeyPressed(evt);
            }
        });

        showPasswordBox.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        showPasswordBox.setLabel("Show Password");
        showPasswordBox.setMinimumSize(new java.awt.Dimension(20, 20));
        showPasswordBox.setName(""); // NOI18N
        showPasswordBox.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                showPasswordBoxItemStateChanged(evt);
            }
        });

        loginErrorLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        loginErrorLabel.setForeground(new java.awt.Color(255, 0, 0));
        loginErrorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginErrorLabel.setText("PLACEHOLDER");

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        label1.setText("Login");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(passwordField, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                    .addComponent(loginButton)
                    .addComponent(usernameField, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                    .addComponent(showPasswordBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(102, Short.MAX_VALUE))
            .addComponent(loginErrorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(loginErrorLabel)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(showPasswordBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(loginButton)
                .addGap(29, 29, 29))
        );

        showPasswordBox.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_loginButtonActionPerformed
    {//GEN-HEADEREND:event_loginButtonActionPerformed
		Connection con = Main.connection();
	   
		try
		{
			boolean usernameIsEmpty = usernameField.getText().isEmpty();
			boolean passwordIsEmpty = passwordField.getPassword().length == 0;

			if (usernameIsEmpty)
			{
				loginErrorLabel.setText("Please insert a username!");
				return;
			}

			if (passwordIsEmpty)
			{
				loginErrorLabel.setText("Please insert a password!");
				return;
			}

			Main.statement = con.prepareStatement("select 1 from it_worker where it_username = ?");
			Main.statement.setString(1, usernameField.getText());
			Main.statement.executeQuery();
			Main.res = Main.statement.getResultSet();
			
			if (!Main.res.next())
			{
				loginErrorLabel.setText("There is no user with that username!");
				return;
			}

			Main.statement = con.prepareStatement("select it_AT from it_worker where it_username = ? and it_password = ?");
			Main.statement.setString(1, usernameField.getText());
			Main.statement.setString(2, new String(passwordField.getPassword()));
			Main.statement.executeQuery();
			Main.res = Main.statement.getResultSet();
			
			if (!Main.res.next())
			{
				loginErrorLabel.setText("Wrong password.");
				return;
			}

			String itAt = Main.res.getString(1);
			loginErrorLabel.setText("");
			User.setLoggedInUser(itAt);

			this.dispose();
			MainWindow.mainWindow();
		}
		catch(SQLException e)
		{
			e.printStackTrace();
			System.exit(-1);
		}
    }//GEN-LAST:event_loginButtonActionPerformed

    private void showPasswordBoxItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_showPasswordBoxItemStateChanged
    {//GEN-HEADEREND:event_showPasswordBoxItemStateChanged
        if (showPasswordBox.getState())
		{
			passwordField.setEchoChar((char)0);
		}
		else
		{
			passwordField.setEchoChar('*');
		}
    }//GEN-LAST:event_showPasswordBoxItemStateChanged

    private void usernameFieldKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_usernameFieldKeyPressed
    {//GEN-HEADEREND:event_usernameFieldKeyPressed
		if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER)
			loginButtonActionPerformed(null);
    }//GEN-LAST:event_usernameFieldKeyPressed

    private void passwordFieldKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_passwordFieldKeyPressed
    {//GEN-HEADEREND:event_passwordFieldKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER)
			loginButtonActionPerformed(null);
    }//GEN-LAST:event_passwordFieldKeyPressed

	/**
	 @param args the command line arguments
	 */
	public static void loginWindow()
	{
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try
		{
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
			{
				if ("Nimbus".equals(info.getName()))
				{
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		}
		catch (ClassNotFoundException ex)
		{
			java.util.logging.Logger.getLogger(LoginWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		catch (InstantiationException ex)
		{
			java.util.logging.Logger.getLogger(LoginWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		catch (IllegalAccessException ex)
		{
			java.util.logging.Logger.getLogger(LoginWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		catch (javax.swing.UnsupportedLookAndFeelException ex)
		{
			java.util.logging.Logger.getLogger(LoginWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable()
		{
			public void run()
			{
				new LoginWindow().setVisible(true);
			}
		});
	}
	
	private void loadCredentials()
	{
		File file = new File(Main.uploadPath());
		
		try
		{
			Scanner scan = new Scanner(file);
			
			while (scan.hasNextLine())
			{
				String data = scan.nextLine();
				
				LinkedList<Pair<Object, Integer>> list = new LinkedList<Pair<Object, Integer>>();
				list.add(new Pair<Object, Integer>(data, Types.CHAR));
				DatabaseQuery query = new DatabaseQuery("select it_username, it_password from it_worker where it_AT = ?", list);
				
				try
				{
					query.execute();
					
					Main.res.next();
					
					//Main.res.getString(1);
					//Main.res.getString(2);
					
					usernameField.setText(Main.res.getString(1));
					passwordField.setText(Main.res.getString(2));
				}
				catch (SQLException e)
				{
					e.printStackTrace();
				}
			}

			scan.close();
		}
		catch(FileNotFoundException e)
		{
			usernameField.setText("");
			passwordField.setText("");
		}
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel loginErrorLabel;
    private javax.swing.JPasswordField passwordField;
    private java.awt.Checkbox showPasswordBox;
    private javax.swing.JTextField usernameField;
    // End of variables declaration//GEN-END:variables
}
